### ISSUE TITLE
unable to create playlist

### ISSUE THREAD

**Issue by rijink7** [khevamann/CordovaAppleMusic#1]
i have tried the command but it returns
Error Domain=MPErrorDomain Code=2 \"The requested operation is not enabled for this device.\" UserInfo={NSLocalizedDescription=The requested operation is not enabled for this device.}.
please help .

**Comment by nada-elhakim** [comment]
I am facing the same problem. How did you solve this?

**Comment by rijink7** [comment]
@nada-elhakim the issue was due to the user was not joined in apple music (did not activated an plan in apple music)
