### ISSUE TITLE
playlist creation

### ISSUE THREAD

**Issue by rijink7** [khevamann/CordovaAppleMusic#2]
i'm facing some issues while i try to create playlist.the problem is that, it creates the playlist successfully but the songs are not there in the playlist.i have given all the corresponding trackIDs for the songs(in an array as your documentation suggested). what might have gone wrong, could you please help me

**Comment by khevamann** [comment]
Here is the code I use to create a playlist. You must make sure that your array of songs are strings. If they are numbers, it will not work. Let me know if this fixes your issue.

let songs = ["72483933","72483933","72483933"]
    appleMusic.requestAuthorization((data) => {
      appleMusic.createPlayList("My Playlist", songs, (data) => {
        console.log("Success", data);
      }, (err) => {
        console.log("Error", err)
      })
    })
  }

**Comment by rijink7** [comment]
thanks it worked .
i have one more doubt does it take time to update songs in playlist coz
when i tested the playlist on apple music it only had few songs after some
time it has updated to same number of songs i have added ? excuse my bad
english

**Comment by khevamann** [comment]
@rijink7 yes it takes a bit of time for apple to update the playlist. The bast you can do it tell your users that not all songs will show up at once.
