### ISSUE TITLE
Is it possible to retrieve the MediaStream of the playing song?

### ISSUE THREAD

**Issue by lone-cloud** [khevamann/CordovaAppleMusic#3]
As the title says. Wondering if it's possible to get the playing https://developer.mozilla.org/en-US/docs/Web/API/MediaStream for music analysis.

**Comment by khevamann** [comment]
This plugin is just for apple music which is only available on iOS, so it is not in the functionality.

**Comment by lone-cloud** [comment]
You'd be surprised to hear that MediaStream has nothing to do with the platform you're on.

Either way, this question/suggestion is no longer relevant.
